spring:
  h2:
    console:
      enabled: true
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
    username: sa
    password:

#spring
#  jpadatabase-platform=org.hibernate.dialect.MySQL5InnoDBDialect
#  #spring.datasource.url=jdbc:mysql://${mysql_address}:${mysql_port}/kubermarket?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
#  spring.datasource.url=jdbc:mysql://localhost:3306/kubermarket?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
#  spring.datasource.username=root
#  spring.datasource.password=123321
#  spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create # ddl 옵션을 무엇으로 할 것인지 (none | create-drop | create | update | validate)
      generate-ddl: true # true 설정 시, 해당 데이터를 근거로 서버 시작 시점에 DDL 문 생성하여 DB 에 적용 (ddl 생성옵션 링크)
      show-sql: true # true 설정 시, 콘솔에 JPA 쿼리를 보여준다.
      properties.hibernate.format_sql: true # true 설정 시, 콘솔에 표시되는 쿼리를 가독성있게 보여준다.
      properties.hibernate.use_sql_comments: false # true 설정 시, 콘솔에 표시되는 쿼리문 위에 어떤 실행을 하려는지 hint 를 보여준다.

file:
  upload:
    directory: "resources/img/"